# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "albums", :force => true do |t|
    t.column "albumName",   :string
    t.column "compilation", :boolean
    t.column "albumAdded",  :datetime
    t.column "artist_id",   :integer
    t.column "genre_id",    :integer
  end

  create_table "artists", :force => true do |t|
    t.column "artistName",  :string
    t.column "compilation", :boolean
  end

  create_table "genres", :force => true do |t|
    t.column "genreName", :string
  end

  create_table "playlists", :force => true do |t|
    t.column "playlistName", :string
  end

  create_table "playlists_tracks", :id => false, :force => true do |t|
    t.column "playlist_id", :integer
    t.column "track_id",    :integer
  end

  add_index "playlists_tracks", ["playlist_id"], :name => "index_playlists_tracks_on_playlist_id"

  create_table "tracks", :force => true do |t|
    t.column "artist_id",     :integer
    t.column "album_id",      :integer
    t.column "genre_id",      :integer
    t.column "trackID",       :integer
    t.column "trackName",     :string
    t.column "trackDuration", :integer
    t.column "trackLocation", :string,   :limit => 2048
    t.column "trackSize",     :integer
    t.column "trackNumber",   :integer
    t.column "compilation",   :boolean
    t.column "trackYear",     :integer
    t.column "trackAdded",    :datetime
  end

  add_index "tracks", ["trackID"], :name => "index_tracks_on_trackID"

end
